name: project_name
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.2
  location: ^5.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logomark1.png  
    - assets/images/salad1.png  
    - assets/images/pizza-slice1.png  
    - assets/images/ice-cream1.png  
    - assets/images/hotdog1.png  
    - assets/images/burger-lettuce1.png  
    - assets/images/Logomark.png  
    - assets/images/BackgroundAnimation.png
    - assets/images/question.png  
  fonts:
    - family: Quicksand-Bolds
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: Quicksand-Light
      fonts:        
        - asset: assets/fonts/Quicksand-Light.ttf
    - family: Quicksand-Medium
      fonts:        
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: Quicksand
      fonts:        
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Quicksand-SemiBold
      fonts:        
        - asset: assets/fonts/Quicksand-SemiBold.ttf
    - family: Quicksand-VariableFont_wght
      fonts:        
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf