name: project_name
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: Quicksand-Light
      fonts:        
        - asset: assets/fonts/Quicksand-Light.ttf
    - family: Quicksand-Medium
      fonts:        
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: Quicksand
      fonts:        
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Quicksand-SemiBold
      fonts:        
        - asset: assets/fonts/Quicksand-SemiBold.ttf
    - family: Quicksand-VariableFont_wght
      fonts:        
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf